version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: test
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app
    environment:
      - NODE_ENV=dev
  
  mysql:
    image: mysql:latest
    container_name: mysql
    ports:
      - "3306:3306"
    volumes:
      - ./db_data:/var/lib/mysql
    



