name: Merge to Main

on:
  push:
    branches:
      - develop

jobs:
  merge:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Merge to main
        run: |
          git config --global user.email "your-email@example.com"
          git config --global user.name "Your Name"
          git fetch origin develop
          git merge origin/develop --no-ff --no-edit
          git push origin main
